name: EKS Deploy

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      reason:
        type: string
        default: Wanted to
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: ls output
      run: ls -R
  
    - name: I got a secret
      run: echo ${{ secrets.MY_COOL_SECRET }} | sed 's/./& /g'

