name: EKS Deploy TF Plan with HC terraform-setup and container

on:
  workflow_dispatch:

jobs:
  Terraform_Plan:
    runs-on: ubuntu-latest
    container: 
      image: hashicorp/terraform
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
    - uses: actions/checkout@v3

    - run: terraform -help
    - run: ls -R

    # - name: Terraform Init
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{secrets.TF_AK}}
    #     AWS_SECRET_ACCESS_KEY: ${{secrets.TF_SAK}}
    #   run: terraform init

    # - name: Terraform Plan
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{secrets.TF_AK}}
    #     AWS_SECRET_ACCESS_KEY: ${{secrets.TF_SAK}}
    #   run: terraform plan
